[package]
name = "sdvrp"
version = "0.1.3"
edition = "2024"
description = "Rust binding of Alkaid-SDVRP: An Efficient Open-Source Solver for the Vehicle Routing Problem with Split Deliveries"
license = "MIT"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
glob = "0.3.1"
